jobs:
  - name: lint_pull_requests_runSh
    type: runSh
    steps:
      - IN: pr_lint_pr_only_gitRepo
        showBuildStatus: true
      - TASK:
        - script: echo Pull request "$PR_LINT_PR_ONLY_GITREPO_PULL_REQUEST"
        - script: echo $PR_LINT_PR_ONLY_GITREPO_PATH
        - script: sleep 60m
